name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  save-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Save kube-apiserver
        run: docker pull registry.k8s.io/kube-apiserver:v1.25.4; docker save registry.k8s.io/kube-apiserver:v1.25.4 -o kube-apiserver.tar.gz
      - name: Save kube-controller-manager
        run: docker pull registry.k8s.io/kube-controller-manager:v1.25.4; docker save registry.k8s.io/kube-controller-manager:v1.25.4 -o kube-controller-manager.tar.gz
      - name: Save kube-scheduler
        run: docker pull registry.k8s.io/kube-scheduler:v1.25.4; docker save registry.k8s.io/kube-scheduler:v1.25.4 -o kube-scheduler.tar.gz
      - name: Save kube-proxy
        run: docker pull registry.k8s.io/kube-proxy:v1.25.4; docker save registry.k8s.io/kube-proxy:v1.25.4 -o kube-proxy.tar.gz
      - name: Save pause
        run: docker pull registry.k8s.io/pause:3.8; docker save registry.k8s.io/pause:3.8 -o pause.tar.gz
      - name: Save etcd
        run: docker pull registry.k8s.io/etcd:3.5.5-0; docker save registry.k8s.io/etcd:3.5.5-0 -o etcd.tar.gz
      - name: Save coredns
        run: docker pull registry.k8s.io/coredns/coredns:v1.9.3; docker save registry.k8s.io/coredns/coredns:v1.9.3 -o coredns.tar.gz
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: v1.25.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.25.4

      # Creates the new release with the binary as a release asset.
      # If the previous Action was skipped, then this keeps the same tag as the
      # previous release.
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "v1.25.4"
          name: "v1.25.4"
          tag_name: v1.25.4
          files: |
            kube-apiserver.tar.gz
            kube-controller-manager.tar.gz
            kube-scheduler.tar.gz
            kube-proxy.tar.gz
            pause.tar.gz
            etcd.tar.gz
            coredns.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
